# Importing numpy

In [20]:
import numpy as np

# Using arrays

In [21]:
arr = np.array([1,2,3])

In [22]:
print(arr[1])

2


# Using matrixes

In [23]:
mat = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

In [24]:
mat.size

6

In [25]:
mat.ndim

2

In [26]:
mat.shape

(2, 3)

In [27]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [28]:
print(mat[:, :2])

[[1 2]
 [4 5]]


# Basic Statistics

In [29]:
a = np.array([1,2,3,4])

In [30]:
a.sum()

10

In [31]:
a.mean()

2.5

In [32]:
a.std()

1.118033988749895

In [33]:
a.var()

1.25

In [34]:
b = np.array([
    [1,2,3,4],
    [10,11,12,13]
])

In [35]:
b.mean(axis=1) # Per row

array([ 2.5, 11.5])

In [36]:
b.mean(axis=0) # Per column

array([5.5, 6.5, 7.5, 8.5])

# Operations - vectorized operations

In [37]:
a = np.arange(5)
b = np.array([10,10,10,10,10])

In [38]:
a + 10

array([10, 11, 12, 13, 14])

In [39]:
a * 10

array([ 0, 10, 20, 30, 40])

In [40]:
a * b

array([ 0, 10, 20, 30, 40])

# Operations - Boolean Arrays

In [41]:
a = np.arange(4)

In [42]:
a

array([0, 1, 2, 3])

In [43]:
a[[0, -1]]

array([0, 3])

In [44]:
a[[True, False, False, True]]

array([0, 3])

In [45]:
a[a >= 2]

array([2, 3])

In [46]:
a[~(a > a.mean())]

array([0, 1])

In [47]:
a[~(a > a.mean()) & a != 0]

array([1])

# Operations - Linear Algebra

In [48]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [49]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [50]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [51]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])